services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
  web:
    build:
      context: ./web
    volumes:
      - ./web:/app
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic
    depends_on:
      - auth
  # nginx service removed